export const enum RecrutementStatus {
  PRE_SELECTED = 'PRE_SELECTED',

  HR_INTERVIEW_FIXED = 'HR_INTERVIEW_FIXED',

  HR_INTERVIEW_PASSED = 'HR_INTERVIEW_PASSED',

  HR_INTERVIEW_FAILED = 'HR_INTERVIEW_FAILED',
}
